/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.44.                      *
*        Compiled Nov 10 2017, 08:52:20                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: GPS_WIFI                                              *
* Dimensions:  67 * 76                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmGPS_WIFI;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsGPS_WIFI[] = {
#if (GUI_USE_ARGB == 0)
  0x000000, 0xFFFFFF
#else
  0xFF000000, 0xFFFFFFFF
#endif

};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalGPS_WIFI = {
  2,  // Number of entries
  0,  // No transparency
  &_ColorsGPS_WIFI[0]
};

static GUI_CONST_STORAGE unsigned char _acGPS_WIFI[] = {
  /* RLE: 568 Pixels @ 000,000 */ 254, 0x00, 254, 0x00, 60, 0x00, 
  /* RLE: 006 Pixels @ 032,008 */ 6, 0x01, 
  /* RLE: 057 Pixels @ 038,008 */ 57, 0x00, 
  /* RLE: 015 Pixels @ 028,009 */ 15, 0x01, 
  /* RLE: 048 Pixels @ 043,009 */ 48, 0x00, 
  /* RLE: 022 Pixels @ 024,010 */ 22, 0x01, 
  /* RLE: 043 Pixels @ 046,010 */ 43, 0x00, 
  /* RLE: 026 Pixels @ 022,011 */ 26, 0x01, 
  /* RLE: 040 Pixels @ 048,011 */ 40, 0x00, 
  /* RLE: 028 Pixels @ 021,012 */ 28, 0x01, 
  /* RLE: 038 Pixels @ 049,012 */ 38, 0x00, 
  /* RLE: 009 Pixels @ 020,013 */ 9, 0x01, 
  /* RLE: 012 Pixels @ 029,013 */ 12, 0x00, 
  /* RLE: 010 Pixels @ 041,013 */ 10, 0x01, 
  /* RLE: 034 Pixels @ 051,013 */ 34, 0x00, 
  /* RLE: 008 Pixels @ 018,014 */ 8, 0x01, 
  /* RLE: 018 Pixels @ 026,014 */ 18, 0x00, 
  /* RLE: 008 Pixels @ 044,014 */ 8, 0x01, 
  /* RLE: 032 Pixels @ 052,014 */ 32, 0x00, 
  /* RLE: 007 Pixels @ 017,015 */ 7, 0x01, 
  /* RLE: 010 Pixels @ 024,015 */ 10, 0x00, 
  /* ABS: 002 Pixels @ 034,015 */ 0, 2, 0x01, 0x01, 
  /* RLE: 010 Pixels @ 036,015 */ 10, 0x00, 
  /* RLE: 007 Pixels @ 046,015 */ 7, 0x01, 
  /* RLE: 030 Pixels @ 053,015 */ 30, 0x00, 
  /* RLE: 007 Pixels @ 016,016 */ 7, 0x01, 
  /* RLE: 006 Pixels @ 023,016 */ 6, 0x00, 
  /* RLE: 012 Pixels @ 029,016 */ 12, 0x01, 
  /* RLE: 006 Pixels @ 041,016 */ 6, 0x00, 
  /* RLE: 007 Pixels @ 047,016 */ 7, 0x01, 
  /* RLE: 028 Pixels @ 054,016 */ 28, 0x00, 
  /* RLE: 006 Pixels @ 015,017 */ 6, 0x01, 
  /* RLE: 006 Pixels @ 021,017 */ 6, 0x00, 
  /* RLE: 016 Pixels @ 027,017 */ 16, 0x01, 
  /* RLE: 006 Pixels @ 043,017 */ 6, 0x00, 
  /* RLE: 006 Pixels @ 049,017 */ 6, 0x01, 
  /* RLE: 027 Pixels @ 055,017 */ 27, 0x00, 
  /* RLE: 005 Pixels @ 015,018 */ 5, 0x01, 
  /* RLE: 005 Pixels @ 020,018 */ 5, 0x00, 
  /* RLE: 020 Pixels @ 025,018 */ 20, 0x01, 
  /* RLE: 005 Pixels @ 045,018 */ 5, 0x00, 
  /* RLE: 006 Pixels @ 050,018 */ 6, 0x01, 
  /* RLE: 025 Pixels @ 056,018 */ 25, 0x00, 
  /* RLE: 005 Pixels @ 014,019 */ 5, 0x01, 
  /* RLE: 004 Pixels @ 019,019 */ 4, 0x00, 
  /* RLE: 023 Pixels @ 023,019 */ 23, 0x01, 
  /* RLE: 005 Pixels @ 046,019 */ 5, 0x00, 
  /* RLE: 005 Pixels @ 051,019 */ 5, 0x01, 
  /* RLE: 026 Pixels @ 056,019 */ 26, 0x00, 
  /* RLE: 003 Pixels @ 015,020 */ 3, 0x01, 
  /* RLE: 004 Pixels @ 018,020 */ 4, 0x00, 
  /* RLE: 009 Pixels @ 022,020 */ 9, 0x01, 
  /* RLE: 008 Pixels @ 031,020 */ 8, 0x00, 
  /* RLE: 009 Pixels @ 039,020 */ 9, 0x01, 
  /* RLE: 004 Pixels @ 048,020 */ 4, 0x00, 
  /* RLE: 003 Pixels @ 052,020 */ 3, 0x01, 
  /* RLE: 033 Pixels @ 055,020 */ 33, 0x00, 
  /* RLE: 007 Pixels @ 021,021 */ 7, 0x01, 
  /* RLE: 013 Pixels @ 028,021 */ 13, 0x00, 
  /* RLE: 008 Pixels @ 041,021 */ 8, 0x01, 
  /* RLE: 038 Pixels @ 049,021 */ 38, 0x00, 
  /* RLE: 007 Pixels @ 020,022 */ 7, 0x01, 
  /* RLE: 017 Pixels @ 027,022 */ 17, 0x00, 
  /* RLE: 006 Pixels @ 044,022 */ 6, 0x01, 
  /* RLE: 037 Pixels @ 050,022 */ 37, 0x00, 
  /* RLE: 005 Pixels @ 020,023 */ 5, 0x01, 
  /* RLE: 006 Pixels @ 025,023 */ 6, 0x00, 
  /* RLE: 007 Pixels @ 031,023 */ 7, 0x01, 
  /* RLE: 007 Pixels @ 038,023 */ 7, 0x00, 
  /* RLE: 006 Pixels @ 045,023 */ 6, 0x01, 
  /* RLE: 036 Pixels @ 051,023 */ 36, 0x00, 
  /* RLE: 004 Pixels @ 020,024 */ 4, 0x01, 
  /* RLE: 005 Pixels @ 024,024 */ 5, 0x00, 
  /* RLE: 012 Pixels @ 029,024 */ 12, 0x01, 
  /* RLE: 005 Pixels @ 041,024 */ 5, 0x00, 
  /* RLE: 005 Pixels @ 046,024 */ 5, 0x01, 
  /* RLE: 036 Pixels @ 051,024 */ 36, 0x00, 
  /* RLE: 003 Pixels @ 020,025 */ 3, 0x01, 
  /* RLE: 005 Pixels @ 023,025 */ 5, 0x00, 
  /* RLE: 014 Pixels @ 028,025 */ 14, 0x01, 
  /* RLE: 005 Pixels @ 042,025 */ 5, 0x00, 
  /* RLE: 003 Pixels @ 047,025 */ 3, 0x01, 
  /* RLE: 044 Pixels @ 050,025 */ 44, 0x00, 
  /* RLE: 017 Pixels @ 027,026 */ 17, 0x01, 
  /* RLE: 049 Pixels @ 044,026 */ 49, 0x00, 
  /* RLE: 007 Pixels @ 026,027 */ 7, 0x01, 
  /* RLE: 004 Pixels @ 033,027 */ 4, 0x00, 
  /* RLE: 008 Pixels @ 037,027 */ 8, 0x01, 
  /* RLE: 047 Pixels @ 045,027 */ 47, 0x00, 
  /* RLE: 006 Pixels @ 025,028 */ 6, 0x01, 
  /* RLE: 008 Pixels @ 031,028 */ 8, 0x00, 
  /* RLE: 007 Pixels @ 039,028 */ 7, 0x01, 
  /* RLE: 045 Pixels @ 046,028 */ 45, 0x00, 
  /* RLE: 005 Pixels @ 024,029 */ 5, 0x01, 
  /* RLE: 011 Pixels @ 029,029 */ 11, 0x00, 
  /* RLE: 006 Pixels @ 040,029 */ 6, 0x01, 
  /* RLE: 045 Pixels @ 046,029 */ 45, 0x00, 
  /* RLE: 004 Pixels @ 024,030 */ 4, 0x01, 
  /* RLE: 014 Pixels @ 028,030 */ 14, 0x00, 
  /* RLE: 004 Pixels @ 042,030 */ 4, 0x01, 
  /* RLE: 046 Pixels @ 046,030 */ 46, 0x00, 
  /* ABS: 002 Pixels @ 025,031 */ 0, 2, 0x01, 0x01, 
  /* RLE: 007 Pixels @ 027,031 */ 7, 0x00, 
  /* RLE: 003 Pixels @ 034,031 */ 3, 0x01, 
  /* RLE: 006 Pixels @ 037,031 */ 6, 0x00, 
  /* ABS: 002 Pixels @ 043,031 */ 0, 2, 0x01, 0x01, 
  /* RLE: 055 Pixels @ 045,031 */ 55, 0x00, 
  /* RLE: 005 Pixels @ 033,032 */ 5, 0x01, 
  /* RLE: 061 Pixels @ 038,032 */ 61, 0x00, 
  /* RLE: 007 Pixels @ 032,033 */ 7, 0x01, 
  /* RLE: 059 Pixels @ 039,033 */ 59, 0x00, 
  /* RLE: 008 Pixels @ 031,034 */ 8, 0x01, 
  /* RLE: 059 Pixels @ 039,034 */ 59, 0x00, 
  /* RLE: 008 Pixels @ 031,035 */ 8, 0x01, 
  /* RLE: 059 Pixels @ 039,035 */ 59, 0x00, 
  /* RLE: 008 Pixels @ 031,036 */ 8, 0x01, 
  /* RLE: 060 Pixels @ 039,036 */ 60, 0x00, 
  /* RLE: 007 Pixels @ 032,037 */ 7, 0x01, 
  /* RLE: 060 Pixels @ 039,037 */ 60, 0x00, 
  /* RLE: 006 Pixels @ 032,038 */ 6, 0x01, 
  /* RLE: 518 Pixels @ 038,038 */ 254, 0x00, 254, 0x00, 10, 0x00, 
  /* RLE: 004 Pixels @ 020,046 */ 4, 0x01, 
  /* RLE: 007 Pixels @ 024,046 */ 7, 0x00, 
  /* RLE: 007 Pixels @ 031,046 */ 7, 0x01, 
  /* RLE: 009 Pixels @ 038,046 */ 9, 0x00, 
  /* RLE: 005 Pixels @ 047,046 */ 5, 0x01, 
  /* RLE: 033 Pixels @ 052,046 */ 33, 0x00, 
  /* RLE: 007 Pixels @ 018,047 */ 7, 0x01, 
  /* RLE: 006 Pixels @ 025,047 */ 6, 0x00, 
  /* RLE: 009 Pixels @ 031,047 */ 9, 0x01, 
  /* RLE: 006 Pixels @ 040,047 */ 6, 0x00, 
  /* RLE: 007 Pixels @ 046,047 */ 7, 0x01, 
  /* RLE: 031 Pixels @ 053,047 */ 31, 0x00, 
  /* RLE: 010 Pixels @ 017,048 */ 10, 0x01, 
  /* RLE: 004 Pixels @ 027,048 */ 4, 0x00, 
  /* RLE: 010 Pixels @ 031,048 */ 10, 0x01, 
  /* RLE: 004 Pixels @ 041,048 */ 4, 0x00, 
  /* RLE: 009 Pixels @ 045,048 */ 9, 0x01, 
  /* RLE: 029 Pixels @ 054,048 */ 29, 0x00, 
  /* RLE: 011 Pixels @ 016,049 */ 11, 0x01, 
  /* RLE: 004 Pixels @ 027,049 */ 4, 0x00, 
  /* RLE: 010 Pixels @ 031,049 */ 10, 0x01, 
  /* RLE: 004 Pixels @ 041,049 */ 4, 0x00, 
  /* RLE: 010 Pixels @ 045,049 */ 10, 0x01, 
  /* RLE: 028 Pixels @ 055,049 */ 28, 0x00, 
  /* RLE: 003 Pixels @ 016,050 */ 3, 0x01, 
  /* RLE: 005 Pixels @ 019,050 */ 5, 0x00, 
  /* RLE: 004 Pixels @ 024,050 */ 4, 0x01, 
  /* RLE: 003 Pixels @ 028,050 */ 3, 0x00, 
  /* RLE: 003 Pixels @ 031,050 */ 3, 0x01, 
  /* RLE: 004 Pixels @ 034,050 */ 4, 0x00, 
  /* RLE: 004 Pixels @ 038,050 */ 4, 0x01, 
  /* RLE: 003 Pixels @ 042,050 */ 3, 0x00, 
  /* ABS: 002 Pixels @ 045,050 */ 0, 2, 0x01, 0x01, 
  /* RLE: 005 Pixels @ 047,050 */ 5, 0x00, 
  /* RLE: 003 Pixels @ 052,050 */ 3, 0x01, 
  /* RLE: 027 Pixels @ 055,050 */ 27, 0x00, 
  /* RLE: 003 Pixels @ 015,051 */ 3, 0x01, 
  /* RLE: 007 Pixels @ 018,051 */ 7, 0x00, 
  /* RLE: 003 Pixels @ 025,051 */ 3, 0x01, 
  /* RLE: 003 Pixels @ 028,051 */ 3, 0x00, 
  /* RLE: 003 Pixels @ 031,051 */ 3, 0x01, 
  /* RLE: 005 Pixels @ 034,051 */ 5, 0x00, 
  /* RLE: 003 Pixels @ 039,051 */ 3, 0x01, 
  /* RLE: 003 Pixels @ 042,051 */ 3, 0x00, 
  /* ABS: 002 Pixels @ 045,051 */ 0, 2, 0x01, 0x01, 
  /* RLE: 005 Pixels @ 047,051 */ 5, 0x00, 
  /* RLE: 003 Pixels @ 052,051 */ 3, 0x01, 
  /* RLE: 027 Pixels @ 055,051 */ 27, 0x00, 
  /* RLE: 003 Pixels @ 015,052 */ 3, 0x01, 
  /* RLE: 013 Pixels @ 018,052 */ 13, 0x00, 
  /* RLE: 003 Pixels @ 031,052 */ 3, 0x01, 
  /* RLE: 005 Pixels @ 034,052 */ 5, 0x00, 
  /* RLE: 003 Pixels @ 039,052 */ 3, 0x01, 
  /* RLE: 003 Pixels @ 042,052 */ 3, 0x00, 
  /* RLE: 003 Pixels @ 045,052 */ 3, 0x01, 
  /* RLE: 034 Pixels @ 048,052 */ 34, 0x00, 
  /* RLE: 003 Pixels @ 015,053 */ 3, 0x01, 
  /* RLE: 013 Pixels @ 018,053 */ 13, 0x00, 
  /* RLE: 003 Pixels @ 031,053 */ 3, 0x01, 
  /* RLE: 005 Pixels @ 034,053 */ 5, 0x00, 
  /* RLE: 003 Pixels @ 039,053 */ 3, 0x01, 
  /* RLE: 003 Pixels @ 042,053 */ 3, 0x00, 
  /* RLE: 005 Pixels @ 045,053 */ 5, 0x01, 
  /* RLE: 032 Pixels @ 050,053 */ 32, 0x00, 
  /* RLE: 003 Pixels @ 015,054 */ 3, 0x01, 
  /* RLE: 013 Pixels @ 018,054 */ 13, 0x00, 
  /* RLE: 003 Pixels @ 031,054 */ 3, 0x01, 
  /* RLE: 003 Pixels @ 034,054 */ 3, 0x00, 
  /* RLE: 004 Pixels @ 037,054 */ 4, 0x01, 
  /* RLE: 004 Pixels @ 041,054 */ 4, 0x00, 
  /* RLE: 008 Pixels @ 045,054 */ 8, 0x01, 
  /* RLE: 028 Pixels @ 053,054 */ 28, 0x00, 
  /* RLE: 004 Pixels @ 014,055 */ 4, 0x01, 
  /* RLE: 004 Pixels @ 018,055 */ 4, 0x00, 
  /* RLE: 006 Pixels @ 022,055 */ 6, 0x01, 
  /* RLE: 003 Pixels @ 028,055 */ 3, 0x00, 
  /* RLE: 010 Pixels @ 031,055 */ 10, 0x01, 
  /* RLE: 005 Pixels @ 041,055 */ 5, 0x00, 
  /* RLE: 008 Pixels @ 046,055 */ 8, 0x01, 
  /* RLE: 027 Pixels @ 054,055 */ 27, 0x00, 
  /* RLE: 004 Pixels @ 014,056 */ 4, 0x01, 
  /* RLE: 004 Pixels @ 018,056 */ 4, 0x00, 
  /* RLE: 006 Pixels @ 022,056 */ 6, 0x01, 
  /* RLE: 003 Pixels @ 028,056 */ 3, 0x00, 
  /* RLE: 010 Pixels @ 031,056 */ 10, 0x01, 
  /* RLE: 007 Pixels @ 041,056 */ 7, 0x00, 
  /* RLE: 007 Pixels @ 048,056 */ 7, 0x01, 
  /* RLE: 027 Pixels @ 055,056 */ 27, 0x00, 
  /* RLE: 003 Pixels @ 015,057 */ 3, 0x01, 
  /* RLE: 004 Pixels @ 018,057 */ 4, 0x00, 
  /* RLE: 006 Pixels @ 022,057 */ 6, 0x01, 
  /* RLE: 003 Pixels @ 028,057 */ 3, 0x00, 
  /* RLE: 009 Pixels @ 031,057 */ 9, 0x01, 
  /* RLE: 011 Pixels @ 040,057 */ 11, 0x00, 
  /* RLE: 004 Pixels @ 051,057 */ 4, 0x01, 
  /* RLE: 027 Pixels @ 055,057 */ 27, 0x00, 
  /* RLE: 003 Pixels @ 015,058 */ 3, 0x01, 
  /* RLE: 007 Pixels @ 018,058 */ 7, 0x00, 
  /* RLE: 003 Pixels @ 025,058 */ 3, 0x01, 
  /* RLE: 003 Pixels @ 028,058 */ 3, 0x00, 
  /* RLE: 003 Pixels @ 031,058 */ 3, 0x01, 
  /* RLE: 010 Pixels @ 034,058 */ 10, 0x00, 
  /* ABS: 002 Pixels @ 044,058 */ 0, 2, 0x01, 0x01, 
  /* RLE: 006 Pixels @ 046,058 */ 6, 0x00, 
  /* RLE: 004 Pixels @ 052,058 */ 4, 0x01, 
  /* RLE: 026 Pixels @ 056,058 */ 26, 0x00, 
  /* RLE: 003 Pixels @ 015,059 */ 3, 0x01, 
  /* RLE: 008 Pixels @ 018,059 */ 8, 0x00, 
  /* ABS: 008 Pixels @ 026,059 */ 0, 8, 0x01, 0x01, 0x00, 0x00, 0x00, 0x01, 0x01, 0x01, 
  /* RLE: 010 Pixels @ 034,059 */ 10, 0x00, 
  /* RLE: 003 Pixels @ 044,059 */ 3, 0x01, 
  /* RLE: 006 Pixels @ 047,059 */ 6, 0x00, 
  /* RLE: 003 Pixels @ 053,059 */ 3, 0x01, 
  /* RLE: 027 Pixels @ 056,059 */ 27, 0x00, 
  /* RLE: 003 Pixels @ 016,060 */ 3, 0x01, 
  /* RLE: 006 Pixels @ 019,060 */ 6, 0x00, 
  /* RLE: 003 Pixels @ 025,060 */ 3, 0x01, 
  /* RLE: 003 Pixels @ 028,060 */ 3, 0x00, 
  /* RLE: 003 Pixels @ 031,060 */ 3, 0x01, 
  /* RLE: 010 Pixels @ 034,060 */ 10, 0x00, 
  /* RLE: 003 Pixels @ 044,060 */ 3, 0x01, 
  /* RLE: 006 Pixels @ 047,060 */ 6, 0x00, 
  /* RLE: 003 Pixels @ 053,060 */ 3, 0x01, 
  /* RLE: 027 Pixels @ 056,060 */ 27, 0x00, 
  /* RLE: 004 Pixels @ 016,061 */ 4, 0x01, 
  /* RLE: 004 Pixels @ 020,061 */ 4, 0x00, 
  /* RLE: 004 Pixels @ 024,061 */ 4, 0x01, 
  /* RLE: 003 Pixels @ 028,061 */ 3, 0x00, 
  /* RLE: 003 Pixels @ 031,061 */ 3, 0x01, 
  /* RLE: 011 Pixels @ 034,061 */ 11, 0x00, 
  /* RLE: 003 Pixels @ 045,061 */ 3, 0x01, 
  /* RLE: 004 Pixels @ 048,061 */ 4, 0x00, 
  /* RLE: 003 Pixels @ 052,061 */ 3, 0x01, 
  /* RLE: 029 Pixels @ 055,061 */ 29, 0x00, 
  /* RLE: 011 Pixels @ 017,062 */ 11, 0x01, 
  /* RLE: 003 Pixels @ 028,062 */ 3, 0x00, 
  /* RLE: 003 Pixels @ 031,062 */ 3, 0x01, 
  /* RLE: 011 Pixels @ 034,062 */ 11, 0x00, 
  /* RLE: 010 Pixels @ 045,062 */ 10, 0x01, 
  /* RLE: 030 Pixels @ 055,062 */ 30, 0x00, 
  /* RLE: 008 Pixels @ 018,063 */ 8, 0x01, 
  /* RLE: 005 Pixels @ 026,063 */ 5, 0x00, 
  /* RLE: 003 Pixels @ 031,063 */ 3, 0x01, 
  /* RLE: 011 Pixels @ 034,063 */ 11, 0x00, 
  /* RLE: 009 Pixels @ 045,063 */ 9, 0x01, 
  /* RLE: 032 Pixels @ 054,063 */ 32, 0x00, 
  /* RLE: 006 Pixels @ 019,064 */ 6, 0x01, 
  /* RLE: 006 Pixels @ 025,064 */ 6, 0x00, 
  /* RLE: 003 Pixels @ 031,064 */ 3, 0x01, 
  /* RLE: 013 Pixels @ 034,064 */ 13, 0x00, 
  /* RLE: 006 Pixels @ 047,064 */ 6, 0x01, 
  /* RLE: 751 Pixels @ 053,064 */ 254, 0x00, 254, 0x00, 243, 0x00, 
  0
};  // 578 bytes for 5092 pixels

GUI_CONST_STORAGE GUI_BITMAP bmGPS_WIFI = {
  67, // xSize
  76, // ySize
  67, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  _acGPS_WIFI,  // Pointer to picture data (indices)
  &_PalGPS_WIFI,  // Pointer to palette
  GUI_DRAW_RLE8
};

/*************************** End of file ****************************/
