/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.44.                      *
*        Compiled Nov 10 2017, 08:52:20                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: gps_icon                                              *
* Dimensions:  86 * 50                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmgps_icon;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsgps_icon[] = {
#if (GUI_USE_ARGB == 0)
  0x000000, 0xFFFFFF
#else
  0xFF000000, 0xFFFFFFFF
#endif

};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palgps_icon = {
  2,  // Number of entries
  0,  // No transparency
  &_Colorsgps_icon[0]
};

static GUI_CONST_STORAGE unsigned char _acgps_icon[] = {
  /* RLE: 968 Pixels @ 000,000 */ 254, 0x00, 254, 0x00, 254, 0x00, 206, 0x00, 
  /* RLE: 009 Pixels @ 022,011 */ 9, 0x01, 
  /* RLE: 007 Pixels @ 031,011 */ 7, 0x00, 
  /* RLE: 011 Pixels @ 038,011 */ 11, 0x01, 
  /* RLE: 008 Pixels @ 049,011 */ 8, 0x00, 
  /* RLE: 008 Pixels @ 057,011 */ 8, 0x01, 
  /* RLE: 042 Pixels @ 065,011 */ 42, 0x00, 
  /* RLE: 011 Pixels @ 021,012 */ 11, 0x01, 
  /* RLE: 006 Pixels @ 032,012 */ 6, 0x00, 
  /* RLE: 012 Pixels @ 038,012 */ 12, 0x01, 
  /* RLE: 006 Pixels @ 050,012 */ 6, 0x00, 
  /* RLE: 010 Pixels @ 056,012 */ 10, 0x01, 
  /* RLE: 040 Pixels @ 066,012 */ 40, 0x00, 
  /* RLE: 013 Pixels @ 020,013 */ 13, 0x01, 
  /* RLE: 005 Pixels @ 033,013 */ 5, 0x00, 
  /* RLE: 013 Pixels @ 038,013 */ 13, 0x01, 
  /* RLE: 004 Pixels @ 051,013 */ 4, 0x00, 
  /* RLE: 012 Pixels @ 055,013 */ 12, 0x01, 
  /* RLE: 038 Pixels @ 067,013 */ 38, 0x00, 
  /* RLE: 014 Pixels @ 019,014 */ 14, 0x01, 
  /* RLE: 005 Pixels @ 033,014 */ 5, 0x00, 
  /* RLE: 013 Pixels @ 038,014 */ 13, 0x01, 
  /* RLE: 003 Pixels @ 051,014 */ 3, 0x00, 
  /* RLE: 006 Pixels @ 054,014 */ 6, 0x01, 
  /* ABS: 002 Pixels @ 060,014 */ 0, 2, 0x00, 0x00, 
  /* RLE: 005 Pixels @ 062,014 */ 5, 0x01, 
  /* RLE: 037 Pixels @ 067,014 */ 37, 0x00, 
  /* RLE: 005 Pixels @ 018,015 */ 5, 0x01, 
  /* RLE: 006 Pixels @ 023,015 */ 6, 0x00, 
  /* RLE: 004 Pixels @ 029,015 */ 4, 0x01, 
  /* RLE: 005 Pixels @ 033,015 */ 5, 0x00, 
  /* RLE: 003 Pixels @ 038,015 */ 3, 0x01, 
  /* RLE: 006 Pixels @ 041,015 */ 6, 0x00, 
  /* RLE: 004 Pixels @ 047,015 */ 4, 0x01, 
  /* RLE: 003 Pixels @ 051,015 */ 3, 0x00, 
  /* RLE: 004 Pixels @ 054,015 */ 4, 0x01, 
  /* RLE: 006 Pixels @ 058,015 */ 6, 0x00, 
  /* RLE: 004 Pixels @ 064,015 */ 4, 0x01, 
  /* RLE: 036 Pixels @ 068,015 */ 36, 0x00, 
  /* RLE: 004 Pixels @ 018,016 */ 4, 0x01, 
  /* RLE: 008 Pixels @ 022,016 */ 8, 0x00, 
  /* RLE: 004 Pixels @ 030,016 */ 4, 0x01, 
  /* RLE: 004 Pixels @ 034,016 */ 4, 0x00, 
  /* RLE: 003 Pixels @ 038,016 */ 3, 0x01, 
  /* RLE: 006 Pixels @ 041,016 */ 6, 0x00, 
  /* RLE: 004 Pixels @ 047,016 */ 4, 0x01, 
  /* RLE: 003 Pixels @ 051,016 */ 3, 0x00, 
  /* RLE: 004 Pixels @ 054,016 */ 4, 0x01, 
  /* RLE: 006 Pixels @ 058,016 */ 6, 0x00, 
  /* RLE: 004 Pixels @ 064,016 */ 4, 0x01, 
  /* RLE: 036 Pixels @ 068,016 */ 36, 0x00, 
  /* RLE: 004 Pixels @ 018,017 */ 4, 0x01, 
  /* RLE: 008 Pixels @ 022,017 */ 8, 0x00, 
  /* ABS: 002 Pixels @ 030,017 */ 0, 2, 0x01, 0x01, 
  /* RLE: 006 Pixels @ 032,017 */ 6, 0x00, 
  /* RLE: 003 Pixels @ 038,017 */ 3, 0x01, 
  /* RLE: 006 Pixels @ 041,017 */ 6, 0x00, 
  /* RLE: 005 Pixels @ 047,017 */ 5, 0x01, 
  /* ABS: 002 Pixels @ 052,017 */ 0, 2, 0x00, 0x00, 
  /* RLE: 004 Pixels @ 054,017 */ 4, 0x01, 
  /* RLE: 007 Pixels @ 058,017 */ 7, 0x00, 
  /* ABS: 002 Pixels @ 065,017 */ 0, 2, 0x01, 0x01, 
  /* RLE: 037 Pixels @ 067,017 */ 37, 0x00, 
  /* RLE: 003 Pixels @ 018,018 */ 3, 0x01, 
  /* RLE: 017 Pixels @ 021,018 */ 17, 0x00, 
  /* RLE: 003 Pixels @ 038,018 */ 3, 0x01, 
  /* RLE: 007 Pixels @ 041,018 */ 7, 0x00, 
  /* RLE: 004 Pixels @ 048,018 */ 4, 0x01, 
  /* ABS: 002 Pixels @ 052,018 */ 0, 2, 0x00, 0x00, 
  /* RLE: 006 Pixels @ 054,018 */ 6, 0x01, 
  /* RLE: 043 Pixels @ 060,018 */ 43, 0x00, 
  /* RLE: 004 Pixels @ 017,019 */ 4, 0x01, 
  /* RLE: 017 Pixels @ 021,019 */ 17, 0x00, 
  /* RLE: 003 Pixels @ 038,019 */ 3, 0x01, 
  /* RLE: 006 Pixels @ 041,019 */ 6, 0x00, 
  /* RLE: 005 Pixels @ 047,019 */ 5, 0x01, 
  /* RLE: 003 Pixels @ 052,019 */ 3, 0x00, 
  /* RLE: 008 Pixels @ 055,019 */ 8, 0x01, 
  /* RLE: 040 Pixels @ 063,019 */ 40, 0x00, 
  /* RLE: 004 Pixels @ 017,020 */ 4, 0x01, 
  /* RLE: 017 Pixels @ 021,020 */ 17, 0x00, 
  /* RLE: 003 Pixels @ 038,020 */ 3, 0x01, 
  /* RLE: 005 Pixels @ 041,020 */ 5, 0x00, 
  /* RLE: 005 Pixels @ 046,020 */ 5, 0x01, 
  /* RLE: 004 Pixels @ 051,020 */ 4, 0x00, 
  /* RLE: 010 Pixels @ 055,020 */ 10, 0x01, 
  /* RLE: 038 Pixels @ 065,020 */ 38, 0x00, 
  /* RLE: 004 Pixels @ 017,021 */ 4, 0x01, 
  /* RLE: 006 Pixels @ 021,021 */ 6, 0x00, 
  /* RLE: 007 Pixels @ 027,021 */ 7, 0x01, 
  /* RLE: 004 Pixels @ 034,021 */ 4, 0x00, 
  /* RLE: 013 Pixels @ 038,021 */ 13, 0x01, 
  /* RLE: 005 Pixels @ 051,021 */ 5, 0x00, 
  /* RLE: 010 Pixels @ 056,021 */ 10, 0x01, 
  /* RLE: 037 Pixels @ 066,021 */ 37, 0x00, 
  /* RLE: 004 Pixels @ 017,022 */ 4, 0x01, 
  /* RLE: 005 Pixels @ 021,022 */ 5, 0x00, 
  /* RLE: 008 Pixels @ 026,022 */ 8, 0x01, 
  /* RLE: 004 Pixels @ 034,022 */ 4, 0x00, 
  /* RLE: 012 Pixels @ 038,022 */ 12, 0x01, 
  /* RLE: 007 Pixels @ 050,022 */ 7, 0x00, 
  /* RLE: 010 Pixels @ 057,022 */ 10, 0x01, 
  /* RLE: 036 Pixels @ 067,022 */ 36, 0x00, 
  /* RLE: 004 Pixels @ 017,023 */ 4, 0x01, 
  /* RLE: 005 Pixels @ 021,023 */ 5, 0x00, 
  /* RLE: 008 Pixels @ 026,023 */ 8, 0x01, 
  /* RLE: 004 Pixels @ 034,023 */ 4, 0x00, 
  /* RLE: 011 Pixels @ 038,023 */ 11, 0x01, 
  /* RLE: 011 Pixels @ 049,023 */ 11, 0x00, 
  /* RLE: 008 Pixels @ 060,023 */ 8, 0x01, 
  /* RLE: 035 Pixels @ 068,023 */ 35, 0x00, 
  /* RLE: 004 Pixels @ 017,024 */ 4, 0x01, 
  /* RLE: 005 Pixels @ 021,024 */ 5, 0x00, 
  /* RLE: 008 Pixels @ 026,024 */ 8, 0x01, 
  /* RLE: 004 Pixels @ 034,024 */ 4, 0x00, 
  /* RLE: 010 Pixels @ 038,024 */ 10, 0x01, 
  /* RLE: 015 Pixels @ 048,024 */ 15, 0x00, 
  /* RLE: 005 Pixels @ 063,024 */ 5, 0x01, 
  /* RLE: 035 Pixels @ 068,024 */ 35, 0x00, 
  /* RLE: 004 Pixels @ 017,025 */ 4, 0x01, 
  /* RLE: 009 Pixels @ 021,025 */ 9, 0x00, 
  /* RLE: 004 Pixels @ 030,025 */ 4, 0x01, 
  /* RLE: 004 Pixels @ 034,025 */ 4, 0x00, 
  /* RLE: 003 Pixels @ 038,025 */ 3, 0x01, 
  /* RLE: 023 Pixels @ 041,025 */ 23, 0x00, 
  /* RLE: 004 Pixels @ 064,025 */ 4, 0x01, 
  /* RLE: 036 Pixels @ 068,025 */ 36, 0x00, 
  /* RLE: 004 Pixels @ 018,026 */ 4, 0x01, 
  /* RLE: 009 Pixels @ 022,026 */ 9, 0x00, 
  /* RLE: 003 Pixels @ 031,026 */ 3, 0x01, 
  /* RLE: 004 Pixels @ 034,026 */ 4, 0x00, 
  /* RLE: 003 Pixels @ 038,026 */ 3, 0x01, 
  /* RLE: 012 Pixels @ 041,026 */ 12, 0x00, 
  /* RLE: 004 Pixels @ 053,026 */ 4, 0x01, 
  /* RLE: 008 Pixels @ 057,026 */ 8, 0x00, 
  /* RLE: 003 Pixels @ 065,026 */ 3, 0x01, 
  /* RLE: 036 Pixels @ 068,026 */ 36, 0x00, 
  /* RLE: 004 Pixels @ 018,027 */ 4, 0x01, 
  /* RLE: 008 Pixels @ 022,027 */ 8, 0x00, 
  /* RLE: 004 Pixels @ 030,027 */ 4, 0x01, 
  /* RLE: 004 Pixels @ 034,027 */ 4, 0x00, 
  /* RLE: 003 Pixels @ 038,027 */ 3, 0x01, 
  /* RLE: 013 Pixels @ 041,027 */ 13, 0x00, 
  /* RLE: 004 Pixels @ 054,027 */ 4, 0x01, 
  /* RLE: 007 Pixels @ 058,027 */ 7, 0x00, 
  /* RLE: 003 Pixels @ 065,027 */ 3, 0x01, 
  /* RLE: 036 Pixels @ 068,027 */ 36, 0x00, 
  /* RLE: 005 Pixels @ 018,028 */ 5, 0x01, 
  /* RLE: 007 Pixels @ 023,028 */ 7, 0x00, 
  /* RLE: 004 Pixels @ 030,028 */ 4, 0x01, 
  /* RLE: 004 Pixels @ 034,028 */ 4, 0x00, 
  /* RLE: 003 Pixels @ 038,028 */ 3, 0x01, 
  /* RLE: 013 Pixels @ 041,028 */ 13, 0x00, 
  /* RLE: 004 Pixels @ 054,028 */ 4, 0x01, 
  /* RLE: 006 Pixels @ 058,028 */ 6, 0x00, 
  /* RLE: 004 Pixels @ 064,028 */ 4, 0x01, 
  /* RLE: 037 Pixels @ 068,028 */ 37, 0x00, 
  /* RLE: 005 Pixels @ 019,029 */ 5, 0x01, 
  /* RLE: 004 Pixels @ 024,029 */ 4, 0x00, 
  /* RLE: 006 Pixels @ 028,029 */ 6, 0x01, 
  /* RLE: 004 Pixels @ 034,029 */ 4, 0x00, 
  /* RLE: 003 Pixels @ 038,029 */ 3, 0x01, 
  /* RLE: 013 Pixels @ 041,029 */ 13, 0x00, 
  /* RLE: 005 Pixels @ 054,029 */ 5, 0x01, 
  /* RLE: 004 Pixels @ 059,029 */ 4, 0x00, 
  /* RLE: 005 Pixels @ 063,029 */ 5, 0x01, 
  /* RLE: 037 Pixels @ 068,029 */ 37, 0x00, 
  /* RLE: 015 Pixels @ 019,030 */ 15, 0x01, 
  /* RLE: 004 Pixels @ 034,030 */ 4, 0x00, 
  /* RLE: 003 Pixels @ 038,030 */ 3, 0x01, 
  /* RLE: 014 Pixels @ 041,030 */ 14, 0x00, 
  /* RLE: 012 Pixels @ 055,030 */ 12, 0x01, 
  /* RLE: 039 Pixels @ 067,030 */ 39, 0x00, 
  /* RLE: 013 Pixels @ 020,031 */ 13, 0x01, 
  /* RLE: 005 Pixels @ 033,031 */ 5, 0x00, 
  /* RLE: 003 Pixels @ 038,031 */ 3, 0x01, 
  /* RLE: 014 Pixels @ 041,031 */ 14, 0x00, 
  /* RLE: 012 Pixels @ 055,031 */ 12, 0x01, 
  /* RLE: 041 Pixels @ 067,031 */ 41, 0x00, 
  /* RLE: 009 Pixels @ 022,032 */ 9, 0x01, 
  /* RLE: 007 Pixels @ 031,032 */ 7, 0x00, 
  /* RLE: 003 Pixels @ 038,032 */ 3, 0x01, 
  /* RLE: 016 Pixels @ 041,032 */ 16, 0x00, 
  /* RLE: 009 Pixels @ 057,032 */ 9, 0x01, 
  /* RLE: 044 Pixels @ 066,032 */ 44, 0x00, 
  /* RLE: 005 Pixels @ 024,033 */ 5, 0x01, 
  /* RLE: 030 Pixels @ 029,033 */ 30, 0x00, 
  /* RLE: 005 Pixels @ 059,033 */ 5, 0x01, 
  /* RLE: 1398 Pixels @ 064,033 */ 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 128, 0x00, 
  0
};  // 404 bytes for 4300 pixels

GUI_CONST_STORAGE GUI_BITMAP bmgps_icon = {
  86, // xSize
  50, // ySize
  86, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  _acgps_icon,  // Pointer to picture data (indices)
  &_Palgps_icon,  // Pointer to palette
  GUI_DRAW_RLE8
};

/*************************** End of file ****************************/
