/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.40.                      *
*        Compiled Mar 17 2017, 15:33:27                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: wire_gps                                              *
* Dimensions:  80 * 76                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmwire_gps;

/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorswire_gps[] = {
#if (GUI_USE_ARGB == 0)
  0x000000, 0xFFFFFF
#else
  0xFF000000, 0xFFFFFFFF
#endif

};

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palwire_gps = {
  2,  // Number of entries
  0,  // No transparency
  &_Colorswire_gps[0]
};

static GUI_CONST_STORAGE unsigned char _acwire_gps[] = {
  /* RLE: 909 Pixels @ 000,000 */ 254, 0x00, 254, 0x00, 254, 0x00, 147, 0x00, 
  /* ABS: 002 Pixels @ 029,011 */ 0, 2, 0x01, 0x01, 
  /* RLE: 004 Pixels @ 031,011 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 035,011 */ 1, 0x01, 
  /* RLE: 074 Pixels @ 036,011 */ 74, 0x00, 
  /* RLE: 001 Pixels @ 030,012 */ 1, 0x01, 
  /* RLE: 004 Pixels @ 031,012 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 035,012 */ 0, 2, 0x01, 0x01, 
  /* RLE: 072 Pixels @ 037,012 */ 72, 0x00, 
  /* ABS: 002 Pixels @ 029,013 */ 0, 2, 0x01, 0x01, 
  /* RLE: 004 Pixels @ 031,013 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 035,013 */ 0, 2, 0x01, 0x01, 
  /* RLE: 073 Pixels @ 037,013 */ 73, 0x00, 
  /* RLE: 001 Pixels @ 030,014 */ 1, 0x01, 
  /* RLE: 004 Pixels @ 031,014 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 035,014 */ 0, 2, 0x01, 0x01, 
  /* RLE: 071 Pixels @ 037,014 */ 71, 0x00, 
  /* RLE: 004 Pixels @ 028,015 */ 4, 0x01, 
  /* ABS: 005 Pixels @ 032,015 */ 0, 5, 0x00, 0x01, 0x00, 0x01, 0x01, 
  /* RLE: 070 Pixels @ 037,015 */ 70, 0x00, 
  /* RLE: 012 Pixels @ 027,016 */ 12, 0x01, 
  /* RLE: 151 Pixels @ 039,016 */ 151, 0x00, 
  /* ABS: 007 Pixels @ 030,018 */ 0, 7, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 
  /* RLE: 072 Pixels @ 037,018 */ 72, 0x00, 
  /* RLE: 008 Pixels @ 029,019 */ 8, 0x01, 
  /* RLE: 007 Pixels @ 037,019 */ 7, 0x00, 
  /* RLE: 006 Pixels @ 044,019 */ 6, 0x01, 
  /* RLE: 058 Pixels @ 050,019 */ 58, 0x00, 
  /* RLE: 010 Pixels @ 028,020 */ 10, 0x01, 
  /* RLE: 006 Pixels @ 038,020 */ 6, 0x00, 
  /* RLE: 003 Pixels @ 044,020 */ 3, 0x01, 
  /* ABS: 005 Pixels @ 047,020 */ 0, 5, 0x00, 0x00, 0x01, 0x01, 0x01, 
  /* RLE: 057 Pixels @ 052,020 */ 57, 0x00, 
  /* RLE: 008 Pixels @ 029,021 */ 8, 0x01, 
  /* RLE: 006 Pixels @ 037,021 */ 6, 0x00, 
  /* ABS: 002 Pixels @ 043,021 */ 0, 2, 0x01, 0x01, 
  /* RLE: 005 Pixels @ 045,021 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 050,021 */ 0, 2, 0x01, 0x01, 
  /* RLE: 056 Pixels @ 052,021 */ 56, 0x00, 
  /* RLE: 010 Pixels @ 028,022 */ 10, 0x01, 
  /* RLE: 004 Pixels @ 038,022 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 042,022 */ 0, 2, 0x01, 0x01, 
  /* RLE: 007 Pixels @ 044,022 */ 7, 0x00, 
  /* ABS: 002 Pixels @ 051,022 */ 0, 2, 0x01, 0x01, 
  /* RLE: 056 Pixels @ 053,022 */ 56, 0x00, 
  /* RLE: 008 Pixels @ 029,023 */ 8, 0x01, 
  /* RLE: 005 Pixels @ 037,023 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 042,023 */ 0, 2, 0x01, 0x01, 
  /* RLE: 007 Pixels @ 044,023 */ 7, 0x00, 
  /* ABS: 002 Pixels @ 051,023 */ 0, 2, 0x01, 0x01, 
  /* RLE: 056 Pixels @ 053,023 */ 56, 0x00, 
  /* RLE: 008 Pixels @ 029,024 */ 8, 0x01, 
  /* RLE: 005 Pixels @ 037,024 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 042,024 */ 0, 2, 0x01, 0x01, 
  /* RLE: 008 Pixels @ 044,024 */ 8, 0x00, 
  /* RLE: 001 Pixels @ 052,024 */ 1, 0x01, 
  /* RLE: 057 Pixels @ 053,024 */ 57, 0x00, 
  /* RLE: 005 Pixels @ 030,025 */ 5, 0x01, 
  /* RLE: 007 Pixels @ 035,025 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 042,025 */ 1, 0x01, 
  /* RLE: 008 Pixels @ 043,025 */ 8, 0x00, 
  /* ABS: 002 Pixels @ 051,025 */ 0, 2, 0x01, 0x01, 
  /* RLE: 059 Pixels @ 053,025 */ 59, 0x00, 
  /* ABS: 002 Pixels @ 032,026 */ 0, 2, 0x01, 0x01, 
  /* RLE: 008 Pixels @ 034,026 */ 8, 0x00, 
  /* ABS: 002 Pixels @ 042,026 */ 0, 2, 0x01, 0x01, 
  /* RLE: 008 Pixels @ 044,026 */ 8, 0x00, 
  /* RLE: 001 Pixels @ 052,026 */ 1, 0x01, 
  /* RLE: 059 Pixels @ 053,026 */ 59, 0x00, 
  /* ABS: 002 Pixels @ 032,027 */ 0, 2, 0x01, 0x01, 
  /* RLE: 007 Pixels @ 034,027 */ 7, 0x00, 
  /* ABS: 002 Pixels @ 041,027 */ 0, 2, 0x01, 0x01, 
  /* RLE: 008 Pixels @ 043,027 */ 8, 0x00, 
  /* ABS: 002 Pixels @ 051,027 */ 0, 2, 0x01, 0x01, 
  /* RLE: 059 Pixels @ 053,027 */ 59, 0x00, 
  /* ABS: 002 Pixels @ 032,028 */ 0, 2, 0x01, 0x01, 
  /* RLE: 008 Pixels @ 034,028 */ 8, 0x00, 
  /* ABS: 002 Pixels @ 042,028 */ 0, 2, 0x01, 0x01, 
  /* RLE: 008 Pixels @ 044,028 */ 8, 0x00, 
  /* RLE: 001 Pixels @ 052,028 */ 1, 0x01, 
  /* RLE: 059 Pixels @ 053,028 */ 59, 0x00, 
  /* ABS: 002 Pixels @ 032,029 */ 0, 2, 0x01, 0x01, 
  /* RLE: 007 Pixels @ 034,029 */ 7, 0x00, 
  /* ABS: 002 Pixels @ 041,029 */ 0, 2, 0x01, 0x01, 
  /* RLE: 008 Pixels @ 043,029 */ 8, 0x00, 
  /* ABS: 002 Pixels @ 051,029 */ 0, 2, 0x01, 0x01, 
  /* RLE: 059 Pixels @ 053,029 */ 59, 0x00, 
  /* ABS: 002 Pixels @ 032,030 */ 0, 2, 0x01, 0x01, 
  /* RLE: 007 Pixels @ 034,030 */ 7, 0x00, 
  /* ABS: 002 Pixels @ 041,030 */ 0, 2, 0x01, 0x01, 
  /* RLE: 009 Pixels @ 043,030 */ 9, 0x00, 
  /* RLE: 001 Pixels @ 052,030 */ 1, 0x01, 
  /* RLE: 059 Pixels @ 053,030 */ 59, 0x00, 
  /* ABS: 002 Pixels @ 032,031 */ 0, 2, 0x01, 0x01, 
  /* RLE: 007 Pixels @ 034,031 */ 7, 0x00, 
  /* ABS: 002 Pixels @ 041,031 */ 0, 2, 0x01, 0x01, 
  /* RLE: 008 Pixels @ 043,031 */ 8, 0x00, 
  /* ABS: 002 Pixels @ 051,031 */ 0, 2, 0x01, 0x01, 
  /* RLE: 059 Pixels @ 053,031 */ 59, 0x00, 
  /* ABS: 002 Pixels @ 032,032 */ 0, 2, 0x01, 0x01, 
  /* RLE: 006 Pixels @ 034,032 */ 6, 0x00, 
  /* ABS: 002 Pixels @ 040,032 */ 0, 2, 0x01, 0x01, 
  /* RLE: 010 Pixels @ 042,032 */ 10, 0x00, 
  /* RLE: 001 Pixels @ 052,032 */ 1, 0x01, 
  /* RLE: 060 Pixels @ 053,032 */ 60, 0x00, 
  /* ABS: 002 Pixels @ 033,033 */ 0, 2, 0x01, 0x01, 
  /* RLE: 005 Pixels @ 035,033 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 040,033 */ 0, 2, 0x01, 0x01, 
  /* RLE: 009 Pixels @ 042,033 */ 9, 0x00, 
  /* ABS: 002 Pixels @ 051,033 */ 0, 2, 0x01, 0x01, 
  /* RLE: 061 Pixels @ 053,033 */ 61, 0x00, 
  /* RLE: 003 Pixels @ 034,034 */ 3, 0x01, 
  /* ABS: 004 Pixels @ 037,034 */ 0, 4, 0x00, 0x01, 0x01, 0x01, 
  /* RLE: 011 Pixels @ 041,034 */ 11, 0x00, 
  /* RLE: 001 Pixels @ 052,034 */ 1, 0x01, 
  /* RLE: 061 Pixels @ 053,034 */ 61, 0x00, 
  /* RLE: 006 Pixels @ 034,035 */ 6, 0x01, 
  /* RLE: 011 Pixels @ 040,035 */ 11, 0x00, 
  /* ABS: 002 Pixels @ 051,035 */ 0, 2, 0x01, 0x01, 
  /* RLE: 079 Pixels @ 053,035 */ 79, 0x00, 
  /* RLE: 001 Pixels @ 052,036 */ 1, 0x01, 
  /* RLE: 535 Pixels @ 053,036 */ 254, 0x00, 254, 0x00, 27, 0x00, 
  /* RLE: 005 Pixels @ 028,043 */ 5, 0x01, 
  /* RLE: 006 Pixels @ 033,043 */ 6, 0x00, 
  /* RLE: 006 Pixels @ 039,043 */ 6, 0x01, 
  /* RLE: 006 Pixels @ 045,043 */ 6, 0x00, 
  /* RLE: 005 Pixels @ 051,043 */ 5, 0x01, 
  /* RLE: 051 Pixels @ 056,043 */ 51, 0x00, 
  /* RLE: 008 Pixels @ 027,044 */ 8, 0x01, 
  /* RLE: 003 Pixels @ 035,044 */ 3, 0x00, 
  /* RLE: 008 Pixels @ 038,044 */ 8, 0x01, 
  /* RLE: 004 Pixels @ 046,044 */ 4, 0x00, 
  /* RLE: 007 Pixels @ 050,044 */ 7, 0x01, 
  /* RLE: 049 Pixels @ 057,044 */ 49, 0x00, 
  /* RLE: 004 Pixels @ 026,045 */ 4, 0x01, 
  /* RLE: 001 Pixels @ 030,045 */ 1, 0x00, 
  /* RLE: 004 Pixels @ 031,045 */ 4, 0x01, 
  /* RLE: 003 Pixels @ 035,045 */ 3, 0x00, 
  /* RLE: 003 Pixels @ 038,045 */ 3, 0x01, 
  /* RLE: 001 Pixels @ 041,045 */ 1, 0x00, 
  /* RLE: 005 Pixels @ 042,045 */ 5, 0x01, 
  /* ABS: 010 Pixels @ 047,045 */ 0, 10, 0x00, 0x00, 0x01, 0x01, 0x01, 0x00, 0x00, 0x01, 0x01, 0x01, 
  /* RLE: 049 Pixels @ 057,045 */ 49, 0x00, 
  /* RLE: 003 Pixels @ 026,046 */ 3, 0x01, 
  /* RLE: 004 Pixels @ 029,046 */ 4, 0x00, 
  /* RLE: 003 Pixels @ 033,046 */ 3, 0x01, 
  /* ABS: 004 Pixels @ 036,046 */ 0, 4, 0x00, 0x00, 0x01, 0x01, 
  /* RLE: 004 Pixels @ 040,046 */ 4, 0x00, 
  /* RLE: 003 Pixels @ 044,046 */ 3, 0x01, 
  /* ABS: 004 Pixels @ 047,046 */ 0, 4, 0x00, 0x00, 0x01, 0x01, 
  /* RLE: 004 Pixels @ 051,046 */ 4, 0x00, 
  /* RLE: 003 Pixels @ 055,046 */ 3, 0x01, 
  /* RLE: 047 Pixels @ 058,046 */ 47, 0x00, 
  /* RLE: 003 Pixels @ 025,047 */ 3, 0x01, 
  /* RLE: 005 Pixels @ 028,047 */ 5, 0x00, 
  /* RLE: 001 Pixels @ 033,047 */ 1, 0x01, 
  /* RLE: 004 Pixels @ 034,047 */ 4, 0x00, 
  /* RLE: 003 Pixels @ 038,047 */ 3, 0x01, 
  /* RLE: 004 Pixels @ 041,047 */ 4, 0x00, 
  /* ABS: 007 Pixels @ 045,047 */ 0, 7, 0x01, 0x01, 0x00, 0x00, 0x01, 0x01, 0x01, 
  /* RLE: 004 Pixels @ 052,047 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 056,047 */ 1, 0x01, 
  /* RLE: 048 Pixels @ 057,047 */ 48, 0x00, 
  /* RLE: 003 Pixels @ 025,048 */ 3, 0x01, 
  /* RLE: 010 Pixels @ 028,048 */ 10, 0x00, 
  /* ABS: 002 Pixels @ 038,048 */ 0, 2, 0x01, 0x01, 
  /* RLE: 005 Pixels @ 040,048 */ 5, 0x00, 
  /* ABS: 004 Pixels @ 045,048 */ 0, 4, 0x01, 0x01, 0x00, 0x00, 
  /* RLE: 005 Pixels @ 049,048 */ 5, 0x01, 
  /* RLE: 051 Pixels @ 054,048 */ 51, 0x00, 
  /* ABS: 002 Pixels @ 025,049 */ 0, 2, 0x01, 0x01, 
  /* RLE: 011 Pixels @ 027,049 */ 11, 0x00, 
  /* RLE: 003 Pixels @ 038,049 */ 3, 0x01, 
  /* ABS: 009 Pixels @ 041,049 */ 0, 9, 0x00, 0x01, 0x00, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00, 
  /* RLE: 006 Pixels @ 050,049 */ 6, 0x01, 
  /* RLE: 049 Pixels @ 056,049 */ 49, 0x00, 
  /* RLE: 003 Pixels @ 025,050 */ 3, 0x01, 
  /* RLE: 003 Pixels @ 028,050 */ 3, 0x00, 
  /* RLE: 005 Pixels @ 031,050 */ 5, 0x01, 
  /* ABS: 002 Pixels @ 036,050 */ 0, 2, 0x00, 0x00, 
  /* RLE: 009 Pixels @ 038,050 */ 9, 0x01, 
  /* RLE: 004 Pixels @ 047,050 */ 4, 0x00, 
  /* RLE: 006 Pixels @ 051,050 */ 6, 0x01, 
  /* RLE: 048 Pixels @ 057,050 */ 48, 0x00, 
  /* ABS: 002 Pixels @ 025,051 */ 0, 2, 0x01, 0x01, 
  /* RLE: 004 Pixels @ 027,051 */ 4, 0x00, 
  /* RLE: 005 Pixels @ 031,051 */ 5, 0x01, 
  /* ABS: 002 Pixels @ 036,051 */ 0, 2, 0x00, 0x00, 
  /* RLE: 007 Pixels @ 038,051 */ 7, 0x01, 
  /* RLE: 008 Pixels @ 045,051 */ 8, 0x00, 
  /* RLE: 005 Pixels @ 053,051 */ 5, 0x01, 
  /* RLE: 047 Pixels @ 058,051 */ 47, 0x00, 
  /* RLE: 003 Pixels @ 025,052 */ 3, 0x01, 
  /* RLE: 005 Pixels @ 028,052 */ 5, 0x00, 
  /* RLE: 003 Pixels @ 033,052 */ 3, 0x01, 
  /* ABS: 005 Pixels @ 036,052 */ 0, 5, 0x00, 0x00, 0x01, 0x01, 0x01, 
  /* RLE: 008 Pixels @ 041,052 */ 8, 0x00, 
  /* RLE: 001 Pixels @ 049,052 */ 1, 0x01, 
  /* RLE: 006 Pixels @ 050,052 */ 6, 0x00, 
  /* ABS: 002 Pixels @ 056,052 */ 0, 2, 0x01, 0x01, 
  /* RLE: 047 Pixels @ 058,052 */ 47, 0x00, 
  /* RLE: 003 Pixels @ 025,053 */ 3, 0x01, 
  /* RLE: 005 Pixels @ 028,053 */ 5, 0x00, 
  /* RLE: 003 Pixels @ 033,053 */ 3, 0x01, 
  /* ABS: 004 Pixels @ 036,053 */ 0, 4, 0x00, 0x00, 0x01, 0x01, 
  /* RLE: 009 Pixels @ 040,053 */ 9, 0x00, 
  /* ABS: 002 Pixels @ 049,053 */ 0, 2, 0x01, 0x01, 
  /* RLE: 005 Pixels @ 051,053 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 056,053 */ 0, 2, 0x01, 0x01, 
  /* RLE: 048 Pixels @ 058,053 */ 48, 0x00, 
  /* RLE: 003 Pixels @ 026,054 */ 3, 0x01, 
  /* RLE: 004 Pixels @ 029,054 */ 4, 0x00, 
  /* RLE: 003 Pixels @ 033,054 */ 3, 0x01, 
  /* ABS: 005 Pixels @ 036,054 */ 0, 5, 0x00, 0x00, 0x01, 0x01, 0x01, 
  /* RLE: 008 Pixels @ 041,054 */ 8, 0x00, 
  /* RLE: 003 Pixels @ 049,054 */ 3, 0x01, 
  /* RLE: 003 Pixels @ 052,054 */ 3, 0x00, 
  /* RLE: 003 Pixels @ 055,054 */ 3, 0x01, 
  /* RLE: 048 Pixels @ 058,054 */ 48, 0x00, 
  /* RLE: 010 Pixels @ 026,055 */ 10, 0x01, 
  /* ABS: 004 Pixels @ 036,055 */ 0, 4, 0x00, 0x00, 0x01, 0x01, 
  /* RLE: 009 Pixels @ 040,055 */ 9, 0x00, 
  /* RLE: 009 Pixels @ 049,055 */ 9, 0x01, 
  /* RLE: 049 Pixels @ 058,055 */ 49, 0x00, 
  /* RLE: 008 Pixels @ 027,056 */ 8, 0x01, 
  /* RLE: 003 Pixels @ 035,056 */ 3, 0x00, 
  /* RLE: 003 Pixels @ 038,056 */ 3, 0x01, 
  /* RLE: 009 Pixels @ 041,056 */ 9, 0x00, 
  /* RLE: 007 Pixels @ 050,056 */ 7, 0x01, 
  /* RLE: 052 Pixels @ 057,056 */ 52, 0x00, 
  /* RLE: 003 Pixels @ 029,057 */ 3, 0x01, 
  /* RLE: 007 Pixels @ 032,057 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 039,057 */ 1, 0x01, 
  /* RLE: 012 Pixels @ 040,057 */ 12, 0x00, 
  /* ABS: 004 Pixels @ 052,057 */ 0, 4, 0x01, 0x01, 0x00, 0x01, 
  /* RLE: 1464 Pixels @ 056,057 */ 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 254, 0x00, 194, 0x00, 
  0
};  // 657 bytes for 6080 pixels

GUI_CONST_STORAGE GUI_BITMAP bmwire_gps = {
  80, // xSize
  76, // ySize
  80, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  _acwire_gps,  // Pointer to picture data (indices)
  &_Palwire_gps,  // Pointer to palette
  GUI_DRAW_RLE8
};

/*************************** End of file ****************************/
